############################################################################
################################PCA#########################################
############################################################################

#' Classical PCA analysis
#'
#' Performs classical Principal Component Analysis (PCA) on a specmine
#' dataset using \code{stats::prcomp()}.
#'
#' The dataset is expected to contain variables in rows and samples in
#' columns. The data matrix is transposed internally so that samples are
#' treated as observations and variables as features.
#'
#' @param dataset Dataset to analyse. The numeric data matrix must be stored
#'   in \code{dataset$data}, with variables in rows and samples in columns.
#' @param scale Logical indicating whether variables should be scaled before
#'   PCA. The default is \code{TRUE}.
#' @param center Logical indicating whether variables should be centred before
#'   PCA. The default is \code{TRUE}.
#' @param write.file Logical indicating whether the PCA scores and loadings
#'   should be written to CSV files.
#' @param file.out Output file prefix used when
#'   \code{write.file = TRUE}. Two files are created:
#'   \code{<file.out>_scores.csv} and
#'   \code{<file.out>_loadings.csv}.
#' @param ... Additional arguments passed to
#'   \code{stats::prcomp()}.
#'
#' @return An object of class \code{prcomp}. The returned object contains:
#' \itemize{
#'   \item \code{x}: a matrix of PCA scores, with one row per sample;
#'   \item \code{rotation}: a matrix of PCA loadings, with one row per
#'     variable;
#'   \item \code{sdev}: the standard deviations of the principal components;
#'   \item \code{center}: the centring values used by the PCA;
#'   \item \code{scale}: the scaling values used by the PCA when
#'     \code{scale = TRUE};
#'   \item \code{call}: the matched function call.
#' }
#'
#' The row names of \code{x} correspond to sample names when the columns of
#' \code{dataset$data} are named. The row names of \code{rotation} correspond
#' to variable names when the rows of \code{dataset$data} are named.
#'
#' @examples
#' datamat <- matrix(
#'   rnorm(40),
#'   nrow = 4,
#'   ncol = 10,
#'   dimnames = list(
#'     paste0("feature", 1:4),
#'     paste0("sample", 1:10)
#'   )
#' )
#'
#' dataset <- list(data = datamat)
#'
#' pca.result <- pca_analysis_dataset(
#'   dataset,
#'   scale = TRUE,
#'   center = TRUE
#' )
#'
#' dim(pca.result$x)
#' dim(pca.result$rotation)
#'
#' \donttest{
#' file.prefix <- file.path(tempdir(), "pca_example")
#'
#' pca_analysis_dataset(
#'   dataset,
#'   write.file = TRUE,
#'   file.out = file.prefix
#' )
#'
#' file.exists(paste0(file.prefix, "_scores.csv"))
#' file.exists(paste0(file.prefix, "_loadings.csv"))
#' }
#'
#' @export
pca_analysis_dataset = function(
    dataset,
    scale = TRUE,
    center = TRUE,
    write.file = FALSE,
    file.out = NULL,
    ...
) {
  if (!is.list(dataset) || is.null(dataset$data)) {
    stop("'dataset$data' must be provided.")
  }
  
  mat = as.matrix(dataset$data)
  
  if (!is.numeric(mat)) {
    stop("'dataset$data' must contain numeric values.")
  }
  
  if (anyNA(mat) || any(!is.finite(mat))) {
    stop(
      "'dataset$data' contains NA, NaN or Inf values. ",
      "Please clean the data before running PCA."
    )
  }
  
  if (nrow(mat) < 2L || ncol(mat) < 2L) {
    stop(
      "'dataset$data' must contain at least two variables ",
      "and two samples."
    )
  }
  
  if (!is.logical(scale) || length(scale) != 1L || is.na(scale)) {
    stop("'scale' must be a single non-missing logical value.")
  }
  
  if (!is.logical(center) || length(center) != 1L || is.na(center)) {
    stop("'center' must be a single non-missing logical value.")
  }
  
  if (!is.logical(write.file) ||
      length(write.file) != 1L ||
      is.na(write.file)) {
    stop("'write.file' must be a single non-missing logical value.")
  }
  
  pca.result = stats::prcomp(
    t(mat),
    center = center,
    scale. = scale,
    ...
  )
  
  if (isTRUE(write.file)) {
    if (is.null(file.out) ||
        length(file.out) != 1L ||
        !is.character(file.out) ||
        !nzchar(file.out)) {
      stop(
        "Please provide a non-empty 'file.out' when ",
        "write.file = TRUE."
      )
    }
    
    utils::write.csv(
      pca.result$x,
      file = paste0(file.out, "_scores.csv")
    )
    
    utils::write.csv(
      pca.result$rotation,
      file = paste0(file.out, "_loadings.csv")
    )
  }
  
  pca.result
}

#' PCA component importance
#'
#' Calculates the standard deviation, proportion of variance and cumulative
#' proportion of variance explained by selected principal components.
#'
#' The function accepts PCA results generated by
#' \code{pca_analysis_dataset()}, \code{stats::prcomp()} or
#' \code{stats::princomp()}.
#'
#' @param pca.res An object inheriting from class \code{prcomp} or
#'   \code{princomp}.
#' @param pcs Integer vector specifying the principal components to return.
#'   By default, all available components are returned.
#' @param sd Logical indicating whether the standard deviation row should be
#'   returned.
#' @param prop Logical indicating whether the proportion of variance row
#'   should be returned.
#' @param cumul Logical indicating whether the cumulative proportion row
#'   should be returned.
#' @param min.cum Optional numeric value between 0 and 1. When supplied,
#'   components are selected up to the first component whose cumulative
#'   proportion is greater than or equal to this value.
#'
#' @return A numeric matrix with one row for each requested measure:
#' \code{Standard deviation}, \code{Proportion of Variance} and/or
#' \code{Cumulative Proportion}. Columns correspond to the selected principal
#' components.
#'
#' For a \code{prcomp} object, the values are calculated from its
#' \code{sdev} component. For a \code{princomp} object, the same calculation
#' is applied to its \code{sdev} component.
#'
#' @examples
#' datamat <- matrix(
#'   rnorm(40),
#'   nrow = 4,
#'   ncol = 10,
#'   dimnames = list(
#'     paste0("feature", 1:4),
#'     paste0("sample", 1:10)
#'   )
#' )
#'
#' dataset <- list(data = datamat)
#' pca.result <- pca_analysis_dataset(dataset)
#'
#' pca_importance(
#'   pca.result,
#'   pcs = 1:3,
#'   sd = TRUE,
#'   prop = TRUE,
#'   cumul = TRUE
#' )
#'
#' pca_importance(
#'   pca.result,
#'   min.cum = 0.90,
#'   sd = FALSE,
#'   prop = TRUE,
#'   cumul = TRUE
#' )
#'
#' @export
pca_importance = function(
    pca.res,
    pcs = 1:length(pca.res$sdev),
    sd = TRUE,
    prop = TRUE,
    cumul = TRUE,
    min.cum = NULL
) {
  if (!inherits(pca.res, c("prcomp", "princomp"))) {
    stop(
      "'pca.res' must inherit from class 'prcomp' or 'princomp'."
    )
  }
  
  if (!is.logical(sd) || length(sd) != 1L || is.na(sd)) {
    stop("'sd' must be a single non-missing logical value.")
  }
  
  if (!is.logical(prop) || length(prop) != 1L || is.na(prop)) {
    stop("'prop' must be a single non-missing logical value.")
  }
  
  if (!is.logical(cumul) || length(cumul) != 1L || is.na(cumul)) {
    stop("'cumul' must be a single non-missing logical value.")
  }
  
  if (!is.null(min.cum)) {
    if (!is.numeric(min.cum) ||
        length(min.cum) != 1L ||
        is.na(min.cum) ||
        min.cum < 0 ||
        min.cum > 1) {
      stop("'min.cum' must be a single numeric value between 0 and 1.")
    }
  }
  
  rows = integer(0)
  
  if (isTRUE(sd)) {
    rows = c(rows, 1L)
  }
  
  if (isTRUE(prop)) {
    rows = c(rows, 2L)
  }
  
  if (isTRUE(cumul)) {
    rows = c(rows, 3L)
  }
  
  if (!length(rows)) {
    stop(
      "At least one of 'sd', 'prop' or 'cumul' must be TRUE."
    )
  }
  
  sdev = as.numeric(pca.res$sdev)
  
  if (!length(sdev) || any(!is.finite(sdev))) {
    stop("The PCA result does not contain valid component deviations.")
  }
  
  variance = sdev^2
  prop.values = variance / sum(variance)
  cumul.values = cumsum(prop.values)
  
  importance = rbind(
    `Standard deviation` = sdev,
    `Proportion of Variance` = prop.values,
    `Cumulative Proportion` = cumul.values
  )
  
  if (!is.null(min.cum)) {
    selected = which(cumul.values >= min.cum)
    
    if (length(selected)) {
      pcs = seq_len(selected[1])
    } else {
      pcs = seq_along(sdev)
    }
  }
  
  if (!is.numeric(pcs) ||
      anyNA(pcs) ||
      any(pcs < 1) ||
      any(pcs > ncol(importance)) ||
      any(pcs != as.integer(pcs))) {
    stop(
      "'pcs' must contain valid positive integer component indices."
    )
  }
  
  pcs = as.integer(pcs)
  
  importance[rows, pcs, drop = FALSE]
}
############################################################################
# Robust PCA analysis
############################################################################

#' Robust PCA analysis
#'
#' Performs robust Principal Component Analysis using
#' \code{pcaPP::PCAgrid()}.
#'
#' The dataset is expected to contain variables in rows and samples in
#' columns. The data matrix is transposed internally so that samples are
#' treated as observations and variables as features.
#'
#' @param dataset Dataset to analyse. The numeric data matrix must be stored
#'   in \code{dataset$data}, with variables in rows and samples in columns.
#' @param center Method used to centre the data. Common choices are
#'   \code{"mean"}, \code{"median"} or \code{NULL}, according to the options
#'   supported by \code{pcaPP::PCAgrid()}.
#' @param scale Method used to scale the data. Common choices are
#'   \code{"sd"}, \code{"mad"} or \code{NULL}, according to the options
#'   supported by \code{pcaPP::PCAgrid()}.
#' @param k Number of robust principal components to compute.
#' @param write.file Logical indicating whether the robust PCA scores and
#'   loadings should be written to CSV files.
#' @param file.out Output file prefix used when
#'   \code{write.file = TRUE}. The function creates
#'   \code{<file.out>_scores.csv} and
#'   \code{<file.out>_loadings.csv}.
#' @param ... Additional arguments passed to
#'   \code{pcaPP::PCAgrid()}.
#'
#' @return The object returned by \code{pcaPP::PCAgrid()}.
#' Depending on the version of \code{pcaPP}, the result contains robust PCA
#' scores, loadings, component deviations and the centring and scaling
#' information used in the analysis. When scores are available, they can be
#' accessed with \code{pca.result$scores}; loadings can be accessed with
#' \code{pca.result$loadings}.
#'
#' @examples
#' if (requireNamespace("pcaPP", quietly = TRUE)) {
#'   datamat <- matrix(
#'     rnorm(40),
#'     nrow = 4,
#'     ncol = 10,
#'     dimnames = list(
#'       paste0("feature", 1:4),
#'       paste0("sample", 1:10)
#'     )
#'   )
#'
#'   dataset <- list(data = datamat)
#'
#'   robust.result <- pca_robust(
#'     dataset,
#'     center = "median",
#'     scale = "mad",
#'     k = 2
#'   )
#'
#'   is.list(robust.result)
#' }
#'
#' \donttest{
#' if (requireNamespace("pcaPP", quietly = TRUE)) {
#'   datamat <- matrix(
#'     rnorm(40),
#'     nrow = 4,
#'     ncol = 10,
#'     dimnames = list(
#'       paste0("feature", 1:4),
#'       paste0("sample", 1:10)
#'     )
#'   )
#'
#'   dataset <- list(data = datamat)
#'   file.prefix <- file.path(tempdir(), "robust_pca_example")
#'
#'   pca_robust(
#'     dataset,
#'     k = 2,
#'     write.file = TRUE,
#'     file.out = file.prefix
#'   )
#'
#'   file.exists(paste0(file.prefix, "_scores.csv"))
#'   file.exists(paste0(file.prefix, "_loadings.csv"))
#' }
#' }
#'
#' @export
pca_robust = function(
    dataset,
    center = "median",
    scale = "mad",
    k = 10,
    write.file = FALSE,
    file.out = NULL,
    ...
) {
  if (!requireNamespace("pcaPP", quietly = TRUE)) {
    stop(
      "Package 'pcaPP' is required. ",
      "Install it with install.packages('pcaPP')."
    )
  }
  
  if (!is.list(dataset) || is.null(dataset$data)) {
    stop("'dataset$data' must be provided.")
  }
  
  mat = as.matrix(dataset$data)
  
  if (!is.numeric(mat)) {
    stop("'dataset$data' must contain numeric values.")
  }
  
  if (anyNA(mat) || any(!is.finite(mat))) {
    stop(
      "'dataset$data' contains NA, NaN or Inf values. ",
      "Please clean the data before running robust PCA."
    )
  }
  
  if (nrow(mat) < 2L || ncol(mat) < 2L) {
    stop(
      "'dataset$data' must contain at least two variables ",
      "and two samples."
    )
  }
  
  if (!is.numeric(k) ||
      length(k) != 1L ||
      is.na(k) ||
      !is.finite(k) ||
      k < 1 ||
      k != as.integer(k)) {
    stop("'k' must be a single positive integer.")
  }
  
  k = as.integer(k)
  
  max.components = min(nrow(mat), ncol(mat))
  
  if (k > max.components) {
    stop(
      "'k' cannot exceed the smaller of the number of variables ",
      "and samples: ",
      max.components,
      "."
    )
  }
  
  if (!is.logical(write.file) ||
      length(write.file) != 1L ||
      is.na(write.file)) {
    stop("'write.file' must be a single non-missing logical value.")
  }
  
  pca.res = pcaPP::PCAgrid(
    t(mat),
    k = k,
    center = center,
    scale = scale,
    scores = TRUE,
    ...
  )
  
  if (isTRUE(write.file)) {
    if (is.null(file.out) ||
        length(file.out) != 1L ||
        !is.character(file.out) ||
        !nzchar(file.out)) {
      stop(
        "Please provide a non-empty 'file.out' when ",
        "write.file = TRUE."
      )
    }
    
    utils::write.csv(
      pca.res$scores,
      file = paste0(file.out, "_scores.csv")
    )
    
    utils::write.csv(
      pca.res$loadings,
      file = paste0(file.out, "_loadings.csv")
    )
  }
  
  pca.res
}

########################## PCA PLOTS ##################################

#' PCA scree plot
#'
#' Draws a scree plot showing the individual and cumulative percentage of
#' variance explained by the principal components.
#'
#' @param pca.result PCA result object inheriting from class \code{prcomp} or
#'   \code{princomp}.
#' @param num.pcs Optional number of principal components to display. If
#'   \code{NULL}, all available components are displayed.
#' @param cex.leg Numeric value controlling the legend text size.
#' @param leg.pos Legend position accepted by \code{graphics::legend()}.
#' @param lab.text Character vector of length two containing the labels for
#'   the individual and cumulative variance curves.
#' @param fill.col Character or numeric vector of length two containing the
#'   colours for the individual and cumulative variance curves.
#' @param ylab Y-axis label.
#' @param xlab X-axis label.
#' @param ... Additional graphical parameters passed to
#'   \code{graphics::matplot()}.
#'
#' @return No return value; the scree plot is drawn as a side effect.
#'
#' @examples
#' datamat <- matrix(
#'   rnorm(40),
#'   nrow = 4,
#'   ncol = 10,
#'   dimnames = list(
#'     paste0("feature", 1:4),
#'     paste0("sample", 1:10)
#'   )
#' )
#'
#' dataset <- list(data = datamat)
#' pca.result <- pca_analysis_dataset(dataset)
#'
#' pca_screeplot(
#'   pca.result,
#'   num.pcs = 4
#' )
#'
#' @export
pca_screeplot = function(
    pca.result,
    num.pcs = NULL,
    cex.leg = 0.8,
    leg.pos = "right",
    lab.text = c(
      "individual percent",
      "cumulative percent"
    ),
    fill.col = c("blue", "red"),
    ylab = "Percentage",
    xlab = "Principal components",
    ...
) {
  if (!inherits(pca.result, c("prcomp", "princomp"))) {
    stop(
      "'pca.result' must inherit from class 'prcomp' or 'princomp'."
    )
  }
  
  if (length(lab.text) != 2L) {
    stop("'lab.text' must contain exactly two labels.")
  }
  
  if (length(fill.col) != 2L) {
    stop("'fill.col' must contain exactly two colours.")
  }
  
  total.pcs = length(pca.result$sdev)
  
  if (is.null(num.pcs)) {
    num.pcs = total.pcs
  }
  
  if (!is.numeric(num.pcs) ||
      length(num.pcs) != 1L ||
      is.na(num.pcs) ||
      !is.finite(num.pcs) ||
      num.pcs < 1 ||
      num.pcs != as.integer(num.pcs) ||
      num.pcs > total.pcs) {
    stop(
      "'num.pcs' must be a single positive integer not greater ",
      "than the number of available principal components."
    )
  }
  
  num.pcs = as.integer(num.pcs)
  
  importance = pca_importance(
    pca.res = pca.result,
    pcs = seq_len(num.pcs),
    sd = FALSE,
    prop = TRUE,
    cumul = TRUE
  )
  
  individual = as.numeric(
    importance["Proportion of Variance", ]
  ) * 100
  
  cumulative = as.numeric(
    importance["Cumulative Proportion", ]
  ) * 100
  
  old.par = graphics::par(
    mfrow = c(1, 1),
    no.readonly = TRUE
  )
  
  on.exit(
    graphics::par(old.par),
    add = TRUE
  )
  
  graphics::matplot(
    x = seq_len(num.pcs),
    y = cbind(individual, cumulative),
    type = "l",
    lty = 1,
    lwd = 2,
    col = fill.col,
    pch = c(16, 16),
    xaxt = "n",
    ylab = ylab,
    xlab = xlab,
    ...
  )
  
  graphics::axis(
    side = 1,
    at = seq_len(num.pcs),
    labels = paste0("PC", seq_len(num.pcs))
  )
  
  graphics::legend(
    x = leg.pos,
    legend = lab.text,
    col = fill.col,
    lty = 1,
    lwd = 2,
    pch = 16,
    cex = cex.leg,
    bty = "n"
  )
  
  invisible(NULL)
}

#' PCA 2D scores plot
#'
#' Creates a two-dimensional PCA scores plot.
#'
#' The function accepts results from \code{pca_analysis_dataset()},
#' \code{stats::prcomp()} or \code{stats::princomp()}.
#'
#' @param dataset Dataset used in the PCA. Its data matrix must contain
#'   variables in rows and samples in columns.
#' @param pca.result PCA result object of class \code{prcomp} or
#'   \code{princomp}.
#' @param column.class Optional metadata column used for colouring or grouping
#'   samples.
#' @param pcas Integer vector of length two specifying the principal
#'   components to plot.
#' @param labels Logical indicating whether sample labels should be shown.
#' @param ellipses Logical indicating whether group ellipses should be drawn.
#' @param bw Logical indicating whether a black-and-white style should be
#'   used.
#' @param pallette RColorBrewer palette identifier. The argument name
#'   \code{pallette} is retained for compatibility with previous versions.
#' @param leg.pos Legend position.
#' @param xlim Optional numeric vector of length two defining the x-axis
#'   limits.
#' @param ylim Optional numeric vector of length two defining the y-axis
#'   limits.
#'
#' @return A \code{ggplot} object containing the PCA scores plot. The plotted
#'   points represent samples, and their coordinates are the selected PCA
#'   scores. When \code{column.class} is supplied, point colours or shapes
#'   represent the corresponding metadata groups.
#'
#' @examples
#' datamat <- matrix(
#'   rnorm(40),
#'   nrow = 4,
#'   ncol = 10,
#'   dimnames = list(
#'     paste0("feature", 1:4),
#'     paste0("sample", 1:10)
#'   )
#' )
#'
#' dataset <- list(
#'   data = datamat,
#'   metadata = data.frame(
#'     class = factor(rep(c("A", "B"), each = 5))
#'   )
#' )
#'
#' pca.result <- pca_analysis_dataset(dataset)
#'
#' pca_scoresplot2D(
#'   dataset,
#'   pca.result,
#'   column.class = "class",
#'   pcas = c(1, 2),
#'   labels = TRUE
#' )
#'
#' @export
pca_scoresplot2D = function(
    dataset,
    pca.result,
    column.class = NULL,
    pcas = c(1, 2),
    labels = FALSE,
    ellipses = FALSE,
    bw = FALSE,
    pallette = 2,
    leg.pos = "right",
    xlim = NULL,
    ylim = NULL
) {
  if (!inherits(pca.result, c("prcomp", "princomp"))) {
    stop(
      "'pca.result' must inherit from class 'prcomp' or 'princomp'."
    )
  }
  
  if (!is.list(dataset) || is.null(dataset$data)) {
    stop("'dataset$data' must be provided.")
  }
  
  if (!is.matrix(dataset$data) && !is.data.frame(dataset$data)) {
    stop("'dataset$data' must be a matrix or data frame.")
  }
  
  scores = if (inherits(pca.result, "prcomp")) {
    pca.result$x
  } else {
    pca.result$scores
  }
  
  if (is.null(scores) || !is.matrix(scores)) {
    stop("PCA scores are not available in 'pca.result'.")
  }
  
  if (!is.numeric(pcas) ||
      length(pcas) != 2L ||
      anyNA(pcas) ||
      any(!is.finite(pcas)) ||
      any(pcas < 1) ||
      any(pcas != as.integer(pcas)) ||
      any(pcas > ncol(scores))) {
    stop(
      "'pcas' must contain exactly two valid principal component indices."
    )
  }
  
  pcas = as.integer(pcas)
  
  n.samples = nrow(scores)
  
  if (n.samples != ncol(dataset$data)) {
    stop(
      "The number of PCA scores must match the number of samples."
    )
  }
  
  if (!is.logical(labels) ||
      length(labels) != 1L ||
      is.na(labels)) {
    stop("'labels' must be a single non-missing logical value.")
  }
  
  if (!is.logical(ellipses) ||
      length(ellipses) != 1L ||
      is.na(ellipses)) {
    stop("'ellipses' must be a single non-missing logical value.")
  }
  
  if (!is.logical(bw) ||
      length(bw) != 1L ||
      is.na(bw)) {
    stop("'bw' must be a single non-missing logical value.")
  }
  
  if (!is.numeric(xlim) ||
      length(xlim) != 2L ||
      anyNA(xlim) ||
      any(!is.finite(xlim))) {
    if (!is.null(xlim)) {
      stop("'xlim' must be NULL or a numeric vector of length two.")
    }
  }
  
  if (!is.numeric(ylim) ||
      length(ylim) != 2L ||
      anyNA(ylim) ||
      any(!is.finite(ylim))) {
    if (!is.null(ylim)) {
      stop("'ylim' must be NULL or a numeric vector of length two.")
    }
  }
  
  if (is.null(column.class)) {
    group.values = factor(rep("Samples", n.samples))
    has.legend = FALSE
  } else {
    if (is.null(dataset$metadata) ||
        !column.class %in% colnames(dataset$metadata)) {
      stop(
        "'column.class' was not found in 'dataset$metadata'."
      )
    }
    
    group.values = factor(dataset$metadata[[column.class]])
    
    if (length(group.values) != n.samples) {
      stop(
        "'column.class' must contain one value for each sample."
      )
    }
    
    has.legend = TRUE
  }
  
  sample.labels = rownames(scores)
  
  if (is.null(sample.labels)) {
    sample.labels = colnames(dataset$data)
  }
  
  if (is.null(sample.labels)) {
    sample.labels = paste0(
      "Sample",
      seq_len(n.samples)
    )
  }
  
  if (length(sample.labels) != n.samples) {
    sample.labels = paste0(
      "Sample",
      seq_len(n.samples)
    )
  }
  
  pca.points = data.frame(
    x = as.numeric(scores[, pcas[1]]),
    y = as.numeric(scores[, pcas[2]]),
    group = group.values,
    label = sample.labels,
    check.names = FALSE
  )
  
  if (bw) {
    pca.plot = ggplot2::ggplot(
      pca.points,
      ggplot2::aes(
        x = .data[["x"]],
        y = .data[["y"]],
        shape = .data[["group"]]
      )
    ) +
      ggplot2::scale_shape_manual(
        values = seq_along(levels(group.values))
      ) +
      ggplot2::theme_bw()
  } else {
    pca.plot = ggplot2::ggplot(
      pca.points,
      ggplot2::aes(
        x = .data[["x"]],
        y = .data[["y"]],
        colour = .data[["group"]]
      )
    ) +
      ggplot2::scale_colour_brewer(
        type = "qual",
        palette = pallette
      ) +
      ggplot2::theme(
        legend.position = leg.pos
      )
  }
  
  importance = pca_importance(
    pca.res = pca.result,
    pcs = pcas,
    sd = FALSE,
    prop = TRUE,
    cumul = FALSE
  )
  
  explained = as.numeric(
    importance["Proportion of Variance", ]
  ) * 100
  
  pca.plot = pca.plot +
    ggplot2::geom_point(
      size = 3,
      alpha = 0.8
    ) +
    ggplot2::xlab(
      paste0(
        "PC",
        pcas[1],
        " - ",
        formatC(explained[1], format = "f", digits = 2),
        "%"
      )
    ) +
    ggplot2::ylab(
      paste0(
        "PC",
        pcas[2],
        " - ",
        formatC(explained[2], format = "f", digits = 2),
        "%"
      )
    ) +
    ggplot2::ggtitle("PCA 2D Scores Plot")
  
  if (!is.null(xlim)) {
    pca.plot = pca.plot +
      ggplot2::coord_cartesian(
        xlim = xlim
      )
  }
  
  if (!is.null(ylim)) {
    pca.plot = pca.plot +
      ggplot2::coord_cartesian(
        ylim = ylim
      )
  }
  
  if (labels) {
    pca.plot = pca.plot +
      ggplot2::geom_text(
        ggplot2::aes(
          label = .data[["label"]]
        ),
        hjust = -0.1,
        vjust = 0,
        size = 3
      )
  }
  
  if (!bw && ellipses) {
    if (!requireNamespace("ellipse", quietly = TRUE)) {
      stop(
        "Package 'ellipse' is required when ellipses = TRUE."
      )
    }
    
    df.ellipses = calculate_ellipses(pca.points)
    
    if (nrow(df.ellipses) > 0) {
      pca.plot = pca.plot +
        ggplot2::geom_path(
          data = df.ellipses,
          ggplot2::aes(
            x = .data[["x"]],
            y = .data[["y"]],
            colour = .data[["group"]]
          ),
          linewidth = 1,
          linetype = 2,
          inherit.aes = FALSE
        )
    }
  }
  
  if (!has.legend) {
    pca.plot = pca.plot +
      ggplot2::theme(
        legend.position = "none"
      )
  }
  
  pca.plot
}

#' PCA 3D scores plot using rgl
#'
#' Creates an interactive three-dimensional PCA scores plot using
#' \code{rgl}.
#'
#' Samples are represented as points in the selected principal component
#' space. When \code{column.class} is supplied, point colours represent the
#' corresponding metadata groups.
#'
#' @param dataset Dataset used in the PCA. Its data matrix must contain
#'   variables in rows and samples in columns.
#' @param pca.result PCA result object of class \code{prcomp} or
#'   \code{princomp}.
#' @param column.class Optional metadata column used for colouring sample
#'   groups.
#' @param pcas Integer vector of length three specifying the principal
#'   components to plot.
#' @param size Numeric point size passed to \code{rgl::plot3d()}.
#' @param labels Logical indicating whether sample labels should be shown.
#'
#' @return Invisibly returns the object produced by
#'   \code{rgl::plot3d()}; the three-dimensional plot is also drawn as a side
#'   effect.
#'
#' @examples
#' \donttest{
#' if (requireNamespace("rgl", quietly = TRUE)) {
#'   options(rgl.useNULL = TRUE)
#'
#'   datamat <- matrix(
#'     rnorm(40),
#'     nrow = 4,
#'     ncol = 10,
#'     dimnames = list(
#'       paste0("feature", 1:4),
#'       paste0("sample", 1:10)
#'     )
#'   )
#'
#'   dataset <- list(
#'     data = datamat,
#'     metadata = data.frame(
#'       class = factor(rep(c("A", "B"), each = 5))
#'     )
#'   )
#'
#'   pca.result <- pca_analysis_dataset(dataset)
#'
#'   pca_scoresplot3D_rgl(
#'     dataset,
#'     pca.result,
#'     column.class = "class",
#'     pcas = c(1, 2, 3),
#'     labels = TRUE
#'   )
#' }
#' }
#'
#' @export
pca_scoresplot3D_rgl = function(
    dataset,
    pca.result,
    column.class = NULL,
    pcas = c(1, 2, 3),
    size = 1,
    labels = FALSE
) {
  if (!requireNamespace("rgl", quietly = TRUE)) {
    stop(
      "Package 'rgl' is required. ",
      "Install it with install.packages('rgl')."
    )
  }
  
  if (!inherits(pca.result, c("prcomp", "princomp"))) {
    stop(
      "'pca.result' must inherit from class 'prcomp' or 'princomp'."
    )
  }
  
  if (!is.list(dataset) || is.null(dataset$data)) {
    stop("'dataset$data' must be provided.")
  }
  
  scores = if (inherits(pca.result, "prcomp")) {
    pca.result$x
  } else {
    pca.result$scores
  }
  
  if (is.null(scores) || !is.matrix(scores)) {
    stop("PCA scores are not available in 'pca.result'.")
  }
  
  if (!is.numeric(pcas) ||
      length(pcas) != 3L ||
      anyNA(pcas) ||
      any(!is.finite(pcas)) ||
      any(pcas < 1) ||
      any(pcas != as.integer(pcas)) ||
      any(pcas > ncol(scores))) {
    stop(
      "'pcas' must contain exactly three valid principal component indices."
    )
  }
  
  pcas = as.integer(pcas)
  
  if (nrow(scores) != ncol(dataset$data)) {
    stop(
      "The number of PCA scores must match the number of samples."
    )
  }
  
  if (!is.numeric(size) ||
      length(size) != 1L ||
      is.na(size) ||
      !is.finite(size) ||
      size <= 0) {
    stop("'size' must be a single positive numeric value.")
  }
  
  if (!is.logical(labels) ||
      length(labels) != 1L ||
      is.na(labels)) {
    stop("'labels' must be a single non-missing logical value.")
  }
  
  if (is.null(column.class)) {
    group.values = factor(
      rep("Samples", nrow(scores))
    )
  } else {
    if (is.null(dataset$metadata) ||
        !column.class %in% colnames(dataset$metadata)) {
      stop(
        "'column.class' was not found in 'dataset$metadata'."
      )
    }
    
    group.values = droplevels(
      factor(dataset$metadata[[column.class]])
    )
    
    if (length(group.values) != nrow(scores)) {
      stop(
        "'column.class' must contain one value for each sample."
      )
    }
  }
  
  group_colours = grDevices::hcl.colors(
    n = nlevels(group.values),
    palette = "Dark 3"
  )
  
  point_colours = group_colours[
    as.integer(group.values)
  ]
  
  sample.labels = rownames(scores)
  
  if (is.null(sample.labels)) {
    sample.labels = colnames(dataset$data)
  }
  
  if (is.null(sample.labels)) {
    sample.labels = paste0(
      "Sample",
      seq_len(nrow(scores))
    )
  }
  
  if (length(sample.labels) != nrow(scores)) {
    sample.labels = paste0(
      "Sample",
      seq_len(nrow(scores))
    )
  }
  
  pca.plot = rgl::plot3d(
    scores[, pcas, drop = FALSE],
    type = "s",
    col = point_colours,
    size = size,
    xlab = paste0("PC", pcas[1]),
    ylab = paste0("PC", pcas[2]),
    zlab = paste0("PC", pcas[3])
  )
  
  if (labels) {
    rgl::text3d(
      scores[, pcas, drop = FALSE],
      texts = sample.labels,
      cex = 0.6
    )
  }
  
  invisible(pca.plot)
}

#' PCA 3D scores plot
#'
#' Creates an interactive three-dimensional scores plot from a PCA result.
#'
#' @param dataset Dataset used to calculate the PCA.
#' @param pca.result Result returned by \code{pca_analysis_dataset()}.
#' @param column.class Optional metadata column used to colour samples.
#' @param pcas Integer vector of length three specifying the principal
#'   components to plot.
#' @param title Plot title.
#'
#' @return A \code{plotly} htmlwidget.
#'
#' @examples
#' \donttest{
#' if (requireNamespace("plotly", quietly = TRUE)) {
#'   datamat <- matrix(
#'     rnorm(40),
#'     nrow = 5,
#'     ncol = 8
#'   )
#'
#'   dataset <- list(
#'     data = datamat,
#'     metadata = data.frame(
#'       class = factor(rep(c("A", "B"), length.out = 8))
#'     )
#'   )
#'
#'   result <- pca_analysis_dataset(dataset)
#'
#'   pca_scoresplot3D(
#'     dataset,
#'     result,
#'     column.class = "class",
#'     pcas = c(1, 2, 3)
#'   )
#' }
#' }
#'
#' @export
pca_scoresplot3D = function(
    dataset,
    pca.result,
    column.class = NULL,
    pcas = c(1, 2, 3),
    title = "PCA 3D Scores Plot"
) {
  if (!requireNamespace("plotly", quietly = TRUE)) {
    stop(
      paste0(
        "Package 'plotly' is required. ",
        "Install it with install.packages('plotly')."
      ),
      call. = FALSE
    )
  }
  
  if (inherits(pca.result, "prcomp")) {
    scores = pca.result$x
  } else if (inherits(pca.result, "princomp")) {
    scores = pca.result$scores
  } else {
    stop(
      "'pca.result' must inherit from class 'prcomp' or 'princomp'.",
      call. = FALSE
    )
  }
  
  if (is.null(scores) ||
      !is.matrix(scores) ||
      ncol(scores) < 3L) {
    stop(
      "PCA result must contain at least three principal components.",
      call. = FALSE
    )
  }
  
  if (!is.numeric(pcas) ||
      length(pcas) != 3L ||
      anyNA(pcas) ||
      any(!is.finite(pcas)) ||
      any(pcas < 1L) ||
      any(pcas != as.integer(pcas)) ||
      any(pcas > ncol(scores))) {
    stop(
      "'pcas' must contain three valid principal component indices.",
      call. = FALSE
    )
  }
  
  pcas = as.integer(pcas)
  
  df = as.data.frame(
    scores[, pcas, drop = FALSE]
  )
  
  pc_names = paste0(
    "PC",
    pcas
  )
  
  colnames(df) = pc_names
  
  if (!is.null(column.class) &&
      !is.null(dataset$metadata) &&
      column.class %in% colnames(dataset$metadata)) {
    df$Group = as.factor(
      dataset$metadata[, column.class]
    )
  } else {
    df$Group = factor(
      rep("Samples", nrow(df))
    )
  }
  
  x_formula = stats::as.formula(
    paste0("~", pc_names[1L])
  )
  
  y_formula = stats::as.formula(
    paste0("~", pc_names[2L])
  )
  
  z_formula = stats::as.formula(
    paste0("~", pc_names[3L])
  )
  
  plotly::layout(
    plotly::plot_ly(
      data = df,
      x = x_formula,
      y = y_formula,
      z = z_formula,
      color = ~Group,
      type = "scatter3d",
      mode = "markers"
    ),
    title = title,
    scene = list(
      xaxis = list(
        title = pc_names[1L]
      ),
      yaxis = list(
        title = pc_names[2L]
      ),
      zaxis = list(
        title = pc_names[3L]
      )
    )
  )
}
#' PCA biplot
#'
#' Draws a PCA biplot for a \code{prcomp} or \code{princomp} result.
#'
#' @param dataset Dataset used in the PCA.
#' @param pca.result PCA result object.
#' @param cex Text expansion factor.
#' @param legend.cex Legend text size.
#' @param x.colors Colour vector or metadata column name.
#' @param inset Legend inset.
#' @param legend.place Legend position.
#' @param ... Additional arguments passed to the plotting method.
#'
#' @return No return value, called for its side effect of plotting.
#'
#' @examples
#' datamat <- matrix(
#'   rnorm(20),
#'   nrow = 4,
#'   dimnames = list(paste0("x", 1:4), paste0("s", 1:5))
#' )
#' metadata <- data.frame(class = factor(c("A", "A", "B", "B", "A")))
#' dataset <- list(data = datamat, metadata = metadata)
#' pca_res <- pca_analysis_dataset(dataset)
#' pca_biplot(dataset, pca_res)
#'
#' @export
pca_biplot= function(dataset, pca.result, cex = 0.8, legend.cex = 0.8, x.colors = 1, inset = c(0, 0), legend.place = "topright", ...) {
  x.flag = FALSE
  if (x.colors %in% colnames(dataset$metadata)){
    x.colors.meta = x.colors
    x.colors = as.integer(dataset$metadata[, x.colors])
    x.flag = TRUE
    opar=par(xpd=TRUE, mar=par()$mar+c(0,0,0,6))
    on.exit(par(opar))
  }
  
  if (inherits(pca.result, "prcomp")){
    biplot_prcomp_modified(pca.result, cex = cex, x.colors = x.colors, ...)
  } else if (inherits(pca.result, "princomp")){
    biplot_princomp_modified(pca.result, cex = cex, x.colors = x.colors, ...)
  } else {
    stop("Class not supported")
  } 
  if (x.flag){
    legend(legend.place, inset = inset, levels(dataset$metadata[, x.colors.meta]), cex=legend.cex, bty="n", fill = sort(as.integer(factor(levels(dataset$metadata[, x.colors.meta]))))) 
    opar=par(mar=c(5, 4, 4, 2) + 0.1)
    on.exit(par(opar))
  }
}

biplot_princomp_modified = function (x, x.colors, choices = 1L:2L, scale = 1, pc.biplot = FALSE, ...) 
{
  if (length(choices) != 2L) 
    stop("length of choices must be 2")
  if (!length(scores <- x$scores)) 
    stop(gettextf("object '%s' has no scores", deparse(substitute(x))), 
         domain = NA)
  lam <- x$sdev[choices]
  if (is.null(n <- x$n.obs)) 
    n <- 1
  lam <- lam * sqrt(n)
  if (scale < 0 || scale > 1) 
    warning("'scale' is outside [0, 1]")
  if (scale != 0) 
    lam <- lam^scale
  else lam <- 1
  if (pc.biplot) 
    lam <- lam/sqrt(n)
  biplot_default_modified(t(t(scores[, choices])/lam), t(t(x$loadings[, 
                                                                      choices]) * lam), x.colors = x.colors, ...)
  invisible()
}

biplot_prcomp_modified = function (x, x.colors, choices = 1L:2L, scale = 1, pc.biplot = FALSE, ...) 
{
  if (length(choices) != 2L) 
    stop("length of choices must be 2")
  if (!length(scores <- x$x)) 
    stop(gettextf("object '%s' has no scores", deparse(substitute(x))), 
         domain = NA)
  if (is.complex(scores)) 
    stop("biplots are not defined for complex PCA")
  lam <- x$sdev[choices]
  n <- NROW(scores)
  lam <- lam * sqrt(n)
  if (scale < 0 || scale > 1) 
    warning("'scale' is outside [0, 1]")
  if (scale != 0) 
    lam <- lam^scale
  else lam <- 1
  if (pc.biplot) 
    lam <- lam/sqrt(n)
  biplot_default_modified(t(t(scores[, choices])/lam), t(t(x$rotation[, 
                                                                      choices]) * lam), x.colors = x.colors, ...)
  invisible()
}

biplot_default_modified = function (x, y, var.axes = TRUE, col, x.colors, colors, cex = rep(par("cex"), 2), 
                                    xlabs = NULL, ylabs = NULL, expand = 1, xlim = NULL, ylim = NULL, 
                                    arrow.len = 0.1, main = NULL, sub = NULL, xlab = NULL, ylab = NULL, 
                                    ...) 
{
  n <- nrow(x)
  p <- nrow(y)
  if (missing(xlabs)) {
    xlabs <- dimnames(x)[[1L]]
    if (is.null(xlabs)) 
      xlabs <- 1L:n
  }
  xlabs <- as.character(xlabs)
  dimnames(x) <- list(xlabs, dimnames(x)[[2L]])
  if (missing(ylabs)) {
    ylabs <- dimnames(y)[[1L]]
    if (is.null(ylabs)) 
      ylabs <- paste("Var", 1L:p)
  }
  ylabs <- as.character(ylabs)
  dimnames(y) <- list(ylabs, dimnames(y)[[2L]])
  if (length(cex) == 1L) 
    cex <- c(cex, cex)
  if (missing(col)) {
    col <- par("col")
    if (!is.numeric(col)) 
      col <- match(col, palette(), nomatch = 1L)
    col <- c(col, col + 1L)
  }
  else if (length(col) == 1L) 
    col <- c(col, col)
  unsigned.range <- function(x) c(-abs(min(x, na.rm = TRUE)), 
                                  abs(max(x, na.rm = TRUE)))
  rangx1 <- unsigned.range(x[, 1L])
  rangx2 <- unsigned.range(x[, 2L])
  rangy1 <- unsigned.range(y[, 1L])
  rangy2 <- unsigned.range(y[, 2L])
  if (missing(xlim) && missing(ylim)) 
    xlim <- ylim <- rangx1 <- rangx2 <- range(rangx1, rangx2)
  else if (missing(xlim)) 
    xlim <- rangx1
  else if (missing(ylim)) 
    ylim <- rangx2
  ratio <- max(rangy1/rangx1, rangy2/rangx2)/expand
  on.exit(par(op))
  op <- par(pty = "s")
  if (!is.null(main)) 
    op <- c(op, par(mar = par("mar") + c(0, 0, 1, 0)))
  plot(x, type = "n", xlim = xlim, ylim = ylim, col = col[1L], 
       xlab = xlab, ylab = ylab, sub = sub, main = main, ...)
  text(x, xlabs, cex = cex[1L], col = x.colors, ...)
  opar=par(new = TRUE)
  on.exit(par(opar))
  dev.hold()
  on.exit(dev.flush(), add = TRUE)
  plot(y, axes = FALSE, type = "n", xlim = xlim * ratio, ylim = ylim * 
         ratio, xlab = "", ylab = "", col = col[1L], ...)
  axis(3, col = col[2L], ...)
  axis(4, col = col[2L], ...)
  box(col = col[1L])
  text(y, labels = ylabs, cex = cex[2L], col = col[2L], ...)
  if (var.axes) 
    arrows(0, 0, y[, 1L] * 0.8, y[, 2L] * 0.8, col = col[2L], 
           length = arrow.len)
  invisible()
}

#' PCA 3D biplot
#'
#' Creates an interactive 3D PCA biplot using \code{rgl}.
#'
#' @param dataset Dataset used in the PCA.
#' @param pca.result PCA result object.
#' @param column.class Optional metadata column used for colouring groups.
#' @param pcas Principal components to plot.
#'
#' @return No return value, called for its side effect of plotting.
#'
#' @examples
#' \donttest{
#' datamat <- matrix(
#'   rnorm(20),
#'   nrow = 4,
#'   dimnames = list(paste0("x", 1:4), paste0("s", 1:5))
#' )
#' metadata <- data.frame(class = factor(c("A", "A", "B", "B", "A")))
#' dataset <- list(data = datamat, metadata = metadata)
#' pca_res <- pca_analysis_dataset(dataset)
#' pca_biplot3D(dataset, pca_res, column.class = "class")
#' }
#'
#' @export
pca_biplot3D = function(dataset, pca.result, column.class = NULL, pcas = c(1,2,3)){
  if (!requireNamespace("rgl", quietly = TRUE)) {
    stop("Package rgl needed for this function to work. Please install it: install.packages('rgl')",
         call. = FALSE)
  }
  
  if (inherits(pca.result, "prcomp")){
    scores = pca.result$x
    rotation = pca.result$rotation
  } else if (inherits(pca.result, "princomp")){
    scores = pca.result$scores
    rotation = pca.result$loadings
  }  
  pca_scoresplot3D_rgl(dataset, pca.result, column.class, pcas)
  rgl::text3d(scores[,pcas], texts=colnames(dataset$data), cex=0.6)
  rgl::text3d(rotation[,pcas], texts = rownames(rotation), col = "red", cex=0.6)
  coords = NULL
  for (i in 1:nrow(rotation)){
    coords = rbind(coords, rbind(c(0,0,0), rotation[i, pcas]))
  }
  rgl::lines3d(coords, col="red", lwd = 4)
}

#pca pairs plot
#' PCA pairs plot
#'
#' Creates a pairs plot of PCA scores.
#'
#' @param dataset Dataset used in the PCA.
#' @param pca.result PCA result object.
#' @param column.class Optional metadata column used for colouring groups.
#' @param pcas Principal components to include.
#' @param ... Additional arguments passed to \code{GGally::ggpairs()}.
#'
#' @return A \code{ggmatrix} object.
#'
#' @examples
#' \donttest{
#' datamat <- matrix(
#'   rnorm(30),
#'   nrow = 6,
#'   dimnames = list(paste0("x", 1:6), paste0("s", 1:5))
#' )
#' metadata <- data.frame(class = factor(c("A", "A", "B", "B", "A")))
#' dataset <- list(data = datamat, metadata = metadata)
#' pca_res <- pca_analysis_dataset(dataset)
#' pca_pairs_plot(dataset, pca_res, column.class = "class", pcas = 1:3)
#' }
#'
#' @export
pca_pairs_plot = function(dataset, pca.result, column.class = NULL, pcas = c(1,2,3,4,5), ...){
  if (inherits(pca.result, "prcomp")){
    scores = pca.result$x
  } else if (inherits(pca.result, "princomp")){
    scores = pca.result$scores
  }  
  
  if (is.null(column.class)){
    group.values = rep(4, ncol(dataset$data))
  } else {
    group.values = dataset$metadata[,column.class]
  }
  pairs.df = data.frame(scores[,pcas])
  pairs.df$group = group.values
  GGally::ggpairs(pairs.df, mapping = ggplot2::aes(color=group), ...)
}

#kmeans clustering with 3 PCs
#' PCA 3D k-means plot
#'
#' Plots PCA scores in 3D coloured by k-means cluster assignment.
#'
#' @param dataset Dataset used in the PCA.
#' @param pca.result PCA result object.
#' @param num.clusters Number of clusters.
#' @param pcas Principal components to plot.
#' @param kmeans.result Optional precomputed k-means result.
#' @param labels Logical indicating whether sample labels should be shown.
#' @param size Point size.
#' @param ... Additional arguments passed to \code{rgl::plot3d()}.
#'
#' @return No return value, called for its side effect of plotting.
#'
#' @examples
#' \donttest{
#' datamat <- matrix(
#'   rnorm(20),
#'   nrow = 4,
#'   dimnames = list(paste0("x", 1:4), paste0("s", 1:5))
#' )
#' metadata <- data.frame(class = factor(c("A", "A", "B", "B", "A")))
#' dataset <- list(data = datamat, metadata = metadata)
#' pca_res <- pca_analysis_dataset(dataset)
#' pca_kmeans_plot3D(dataset, pca_res, num.clusters = 2)
#' }
#'
#' @export
pca_kmeans_plot3D = function(dataset, pca.result, num.clusters = 3, pcas = c(1,2,3), 
                             kmeans.result = NULL, labels = FALSE, size = 1,...) {
  if (!requireNamespace("rgl", quietly = TRUE)) {
    stop("Package rgl needed for this function to work. Please install it: install.packages('rgl')",
         call. = FALSE)
  }
  
  if (inherits(pca.result, "prcomp")){
    scores = pca.result$x
  } else if (inherits(pca.result, "princomp")){
    scores = pca.result$scores
  }
  
  if (is.null(kmeans.result)){
    kmeans.result = clustering(dataset, method = "kmeans", num.clusters = num.clusters)
  }
  rgl::plot3d(scores[,pcas], type = "s", col = kmeans.result$cluster, size=size,...)
  if (labels){
    rgl::text3d(scores[,pcas],adj = c(1.2,1.2), texts=colnames(dataset$data), cex=0.6)
  }
}

#kmeans clustering with 2 first PCs
#' PCA 2D k-means plot
#'
#' Plots PCA scores in 2D coloured by k-means cluster assignment.
#'
#' @param dataset Dataset used in the PCA.
#' @param pca.result PCA result object.
#' @param num.clusters Number of clusters.
#' @param pcas Principal components to plot.
#' @param kmeans.result Optional precomputed k-means result.
#' @param labels Logical indicating whether sample labels should be shown.
#' @param bw Logical indicating whether a black-and-white style should be used.
#' @param ellipses Logical indicating whether cluster ellipses should be drawn.
#' @param leg.pos Legend position.
#' @param xlim Optional x-axis limits.
#' @param ylim Optional y-axis limits.
#'
#' @return A \code{ggplot} object.
#'
#' @examples
#' \donttest{
#' datamat <- matrix(
#'   rnorm(20),
#'   nrow = 4,
#'   dimnames = list(paste0("x", 1:4), paste0("s", 1:5))
#' )
#' metadata <- data.frame(class = factor(c("A", "A", "B", "B", "A")))
#' dataset <- list(data = datamat, metadata = metadata)
#' pca_res <- pca_analysis_dataset(dataset)
#' pca_kmeans_plot2D(dataset, pca_res, num.clusters = 2)
#' }
#'
#' @export
pca_kmeans_plot2D = function(dataset, pca.result, num.clusters = 3,
                             pcas = c(1,2), kmeans.result = NULL, labels = FALSE, bw=FALSE,
                             ellipses = FALSE, leg.pos = "right", xlim = NULL, ylim = NULL){
  if (inherits(pca.result, "prcomp")){
    scores = pca.result$x
  } else if (inherits(pca.result, "princomp")){
    scores = pca.result$scores
  }
  
  if (is.null(kmeans.result)){
    kmeans.result = clustering(dataset, method = "kmeans", num.clusters = num.clusters)
  }
  pca.points = data.frame(scores[,pcas])
  names(pca.points) = c("x","y")
  pca.points$group = factor(kmeans.result$cluster)
  pca.points$label = colnames(dataset$data)
  if (bw) shape.values = 1:num.clusters
  
  if (bw) pca.plot = ggplot2::ggplot(data = pca.points, ggplot2::aes_string(x='x', y='y',shape='group'))
  else pca.plot = ggplot2::ggplot(data = pca.points, ggplot2::aes_string(x='x', y='y',colour='group')) 
  pca.plot = pca.plot + ggplot2::geom_point(size=3, alpha=.6)
  
  if (bw) pca.plot = pca.plot + ggplot2::scale_shape_manual(values = shape.values)
  else  pca.plot = pca.plot + ggplot2::scale_colour_brewer(palette="Set1") 
  
  pca.plot = pca.plot + ggplot2::xlab(paste("PC",pcas[1],sep="")) + 
    ggplot2::ylab(paste("PC",pcas[2],sep=""))
  
  if (bw) pca.plot = pca.plot + ggplot2::theme_bw()
  else pca.plot = pca.plot + ggplot2::theme(legend.position = leg.pos)
  
  if (!is.null(xlim)){
    pca.plot = pca.plot + ggplot2::xlim(xlim[1],xlim[2])
  }
  if (!is.null(ylim)){
    pca.plot = pca.plot + ggplot2::ylim(ylim[1],ylim[2])
  }
  if (labels){
    pca.plot = pca.plot + ggplot2::geom_text(data = pca.points, ggplot2::aes_string(x='x',y='y',label='label'),hjust=-0.1, vjust=0, size = 3)
  }
  if (!bw & ellipses){
    df.ellipses = calculate_ellipses(pca.points)
    pca.plot = pca.plot + ggplot2::geom_path(data=df.ellipses, ggplot2::aes_string(x='x', y='y',colour='group'), size=1, linetype=2) 
  }
  pca.plot
}

#pca pairs with kmeans clusters plot
#' PCA pairs plot with k-means clusters
#'
#' Creates a pairs plot of PCA scores coloured by k-means cluster assignment.
#'
#' @param dataset Dataset used in the PCA.
#' @param pca.result PCA result object.
#' @param num.clusters Number of clusters.
#' @param kmeans.result Optional precomputed k-means result.
#' @param pcas Principal components to include.
#'
#' @return A \code{ggmatrix} object.
#'
#' @examples
#' \donttest{
#' datamat <- matrix(
#'   rnorm(30),
#'   nrow = 6,
#'   dimnames = list(paste0("x", 1:6), paste0("s", 1:5))
#' )
#' metadata <- data.frame(class = factor(c("A", "A", "B", "B", "A")))
#' dataset <- list(data = datamat, metadata = metadata)
#' pca_res <- pca_analysis_dataset(dataset)
#' pca_pairs_kmeans_plot(dataset, pca_res, num.clusters = 2, pcas = 1:3)
#' }
#'
#' @export
pca_pairs_kmeans_plot = function(dataset, pca.result, num.clusters = 3, kmeans.result = NULL, pcas = c(1,2,3,4,5)){
  if (inherits(pca.result, "prcomp")){
    scores = pca.result$x
  } else if (inherits(pca.result, "princomp")){
    scores = pca.result$scores
  }
  
  if (is.null(kmeans.result)){
    kmeans.result = clustering(dataset, method = "kmeans", num.clusters = num.clusters)
  }
  pairs.df = data.frame(scores[,pcas])
  pairs.df$group = factor(kmeans.result$cluster)
  GGally::ggpairs(pairs.df, mapping = ggplot2::aes(color=group))
}

#draw ellipses
calculate_ellipses = function(data){
  df_ell <- data.frame()
  for(g in levels(data$group)){
    df_ell <- rbind(df_ell, cbind(as.data.frame(with(data[data$group==g,], ellipse::ellipse(cor(x, y), 
                                                                                            scale=c(sd(x),sd(y)), centre=c(mean(x),mean(y))))),group=g))
  }
  df_ell
}